apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-forge-ui-relay-store
  labels:
    app.kubernetes.io/name: rh-forge-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
