{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rh-forge-ui
  labels:
    app.kubernetes.io/name: rh-forge-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: rh-forge-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
