apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: notebook
      type: openclaw
      enabled: true
      image: quay.io/redhat-et/openclaw:csb-openclaw-only-amd64-2026.08.20-1
      providers:
        - gmail-read-proxy
    - name: cuda-sandbox
      type: nemoclaw
      enabled: false
      agent: openclaw
      image: quay.io/rh-ai-quickstart/nemoclaw-sandbox:latest
      providers:
        - nvidia
    - name: toolbox
      type: generic
      enabled: false
      image: base
      providers:
        - nvidia
