apiVersion: saw.redhat.com/v1alpha1
kind: Providers
metadata:
  workspace: cuda-dev
spec:
  providers:
    - name: inference
      type: google-vertex-ai
      model: gemini-2.5-flash
      credentialSecret: inference
      credentialSecretKey: sa_json
      region: us-central1
