source:
  git:
    uri: "https://github.com/NVIDIA/NemoClaw.git"
    ref: "6f3cced4230ae9660c049cc11804daf37797c595" # v0.0.124

build:
  nodeImage: "node:22-trixie-slim"
  maxOpenshellVersion: "0.0.116"

output:
  imageStreamTag: "nemoclaw-cli:latest"
