version: 1

filesystem_policy:
  include_workdir: true
  read_only: [/usr, /lib, /proc, /dev/urandom, /app, /etc, /var/log]
  read_write: [/sandbox, /tmp, /dev/null]

landlock:
  compatibility: best_effort

network_policies:
  brave_search:
    name: brave-search
    endpoints:
      - host: api.search.brave.com
        port: 443
        protocol: rest
        enforcement: enforce
        access: full
  tavily_search:
    name: tavily-search
    endpoints:
      - host: api.tavily.com
        port: 443
        protocol: rest
        enforcement: enforce
        access: full

process:
  run_as_user: sandbox
  run_as_group: sandbox
