apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ (split ":" .Values.output.base.imageStreamTag)._0 }}
  labels:
    {{- include "build-installer.labels" . | nindent 4 }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.build.base.contextDir }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.base.dockerfilePath }}
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.output.base.imageStreamTag }}
  resources:
    limits:
      memory: {{ .Values.resources.limits.memory }}
  triggers: []
