apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ (split ":" .Values.output.agent.imageStreamTag)._0 }}
  labels:
    {{- include "build-installer.labels" . | nindent 4 }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    {{- if .Values.build.agent.contextDir }}
    contextDir: {{ .Values.build.agent.contextDir }}
    {{- end }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.agent.dockerfilePath }}
      forcePull: true
      buildArgs:
        - name: BASE_IMAGE
          value: {{ printf "%s/%s" .Release.Namespace .Values.output.base.imageStreamTag | quote }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.output.agent.imageStreamTag }}
  resources:
    limits:
      memory: {{ .Values.resources.limits.memory }}
  triggers: []
