apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inference
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: inference
  dataFrom:
    - extract:
        key: {{ .Values.vaultPrefix }}/inference
