apiVersion: saw.redhat.com/v1alpha1
kind: Providers
metadata: {}
spec:
  providers:
    - name: brave
      type: brave
      enabled: false
      credentialSecret: web-search
      credentialSecretKey: api_key
