---
apiVersion: v1
kind: Secret
metadata:
  name: saw-integ-vars
  namespace: ${NS}
type: Opaque
# Populate stringData.vars.yml from a completed integrations-vars.example.yml before use.
stringData: {}
