apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: mail-proxy
      type: generic
      enabled: true
      image: quay.io/sallyom/forge-gmail-read-proxy@sha256:dfb6ba5c61745c564035ea49b4e95ed2b21132b49c279c046e8e15e5e9b00f20
      command: "/sandbox/rust-email-proxy"
      exposePort: 18080
      providers:
        - gmail-read
    - name: slack-read
      type: generic
      enabled: false
      image: base
    - name: slack-bot
      type: generic
      enabled: false
      image: base
    - name: slack-send
      type: generic
      enabled: false
      image: base
    - name: web-research
      type: generic
      enabled: false
      image: base
    - name: post-service
      type: generic
      enabled: false
      image: base
